version: 0.1

environment:
  - path: "./cmd/machine-learning-output"
  - input-data-file: "weatherAUS.csv"
  - processed-data-file: "processed-weatherAUS.csv"
  - ml-model-file: "ml-model.joblib"

task:
  - node: node1
    sequential:
      - print:
          - "Started processing data..."
      - execute:
          - "aws s3 sync {{env:s3-bucket-uri}} {{env:path}}"
          - "kaggle datasets download jsphyg/weather-dataset-rattle-package -o -f {{env:input-data-file}} -p {{env:path}}"
          - "unzip -o {{env:path}}/{{env:input-data-file}}.zip -d {{env:path}}"
          - "rm -f {{env:path}}/{{env:input-data-file}}.zip"
          - "chmod +x {{env:path}}/process-data.py"
          - "{{env:path}}/process-data.py {{env:path}}/{{env:input-data-file}} {{env:path}}/{{env:processed-data-file}}"
          - "aws s3 sync {{env:path}} {{env:s3-bucket-uri}}"
      - print:
          - "Completed processing data."

  - node: node2
    sequential:
      - print:
          - "Started training machine learning model..."
      - execute:
          - "aws s3 sync {{env:s3-bucket-uri}} {{env:path}}"
          - "chmod +x {{env:path}}/train-model.py"
          - "{{env:path}}/train-model.py {{env:path}}/{{env:processed-data-file}} {{env:path}}/{{env:ml-model-file}}"
          - "aws s3 sync {{env:path}} {{env:s3-bucket-uri}}"
      - print:
          - "Completed training machine learning model."

  - node: node2
    sequential:
      - print:
          - "Started evaluating machine learning model..."
      - execute:
          - "aws s3 sync {{env:s3-bucket-uri}} {{env:path}}"
          - "chmod +x {{env:path}}/evaluate-model.py"
          - "{{env:path}}/evaluate-model.py {{env:path}}/{{env:processed-data-file}} {{env:path}}/{{env:ml-model-file}}"
          - "aws s3 sync {{env:path}} {{env:s3-bucket-uri}}"
      - print:
          - "Completed evaluating machine learning model."
