apiVersion: batch.ankursoni.github.io/v1
kind: Workflow
metadata:
  name: roiergasias-demo
  namespace: default
spec:
  workflowYAML:
    name: hello-world
    yaml: |
      version: 0.1

      environment:
        - welcome: "Welcome to the demo workflow!"

      task:
        - sequential:
            - print:
                - "Hello"
                - "World!"
            - print:
                - "Hi"
                - "Universe!"
            - environment:
                - greeting: "Warm greetings!"

        - sequential:
            - print:
                - "{{env:welcome}}"
            - execute:
                - "echo {{env:greeting}}"
            - environment:
                - greeting: "Warm greetings again!"

        - sequential:
            - execute:
                - "echo {{env:greeting}}"

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: roiergasias
              image: docker.io/ankursoni/roiergasias-operator:workflow
              command: ["/root/roiergasias", "run", "--file=/root/hello-world/hello-world.yaml"]
              volumeMounts:
                # volume - 'yaml' is automatically created by the operator using a generated configMap
                - name: yaml
                  mountPath: /root/hello-world
