apiVersion: v1
entries:
  roiergasias-operator:
  - apiVersion: v2
    created: "2021-06-27T14:45:42.168284+10:00"
    description: Helm chart for roiergasias operator
    digest: 5f19f8302b6f63388352bc63b76cdee40479771654b767521eeb504a91c53f86
    name: roiergasias-operator
    urls:
    - https://github.com/ankursoni/kubernetes-operator-roiergasias/raw/main/operator/helm/roiergasias-operator-v0.1.1.tgz
    version: v0.1.1
generated: "2021-06-27T14:45:42.16659+10:00"
