apiVersion: batch.ankursoni.github.io/v1
kind: Workflow
metadata:
  name: roiergasias-workflow
  namespace: {{ .Values.namespace }}
spec:
  workflowYAML:
    name: machine-learning
    yaml: |
{{ .Files.Get "machine-learning.yaml" | indent 6 }}
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          imagePullSecrets:
            - name: container-registry-secret
          containers:
            - name: roiergasias
              image: docker.io/ankursoni/roiergasias:local
              command: ["/root/roiergasias", "run", "--file=/root/machine-learning/local/machine-learning.yaml"]
              volumeMounts:
                # volume - 'yaml' is automatically created by the operator using a generated configMap
                - name: yaml
                  mountPath: /root/machine-learning/local
                - name: machine-learning-output
                  mountPath: /root/machine-learning-output
              resources:
                limits:
                  memory: "1000Mi"
                  cpu: "2000m"
          restartPolicy: Never
          volumes:
            - name: machine-learning-output
              hostPath:
                path: {{ .Values.hostPath }}
                type: Directory
