apiVersion: batch/v1
kind: Job
metadata:
  name: roiergasias-job
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      imagePullSecrets:
        - name: container-registry-secret
      containers:
        - name: roiergasias
          image: docker.io/ankursoni/roiergasias:local
          command: ["./cmd/main", "./cmd/machine-learning/machine-learning.yaml"]
          volumeMounts:
            - name: machine-learning
              mountPath: /root/cmd/machine-learning
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
      restartPolicy: Never
      volumes:
        - name: machine-learning
          hostPath:
            path: {{ .Values.hostPath }}
            type: Directory
