# permissions for end users to edit workflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow-editor-role
rules:
- apiGroups:
  - batch.ankursoni.github.io
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.ankursoni.github.io
  resources:
  - workflows/status
  verbs:
  - get
