FROM python:3.9.2

RUN pip install kaggle pandas sklearn joblib \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf ./aws awscliv2.zip || exit 0

WORKDIR /root
COPY ./kaggle.json ./.kaggle/
COPY ./.aws/ ./.aws/
COPY ./main ./cmd/
RUN chmod 0600 ./.kaggle/kaggle.json