apiVersion: batch.ankursoni.github.io/v1
kind: Workflow
metadata:
  name: roiergasias-kubernetes
spec:
  workflowYAML:
    name: hello-world
    yaml: |
      version: 0.1

      environment:
        - welcome: "Welcome to the demo workflow!"

      task:
        - sequential:
          - print:
            - "Hello"
            - "World!"
          - print:
            - "Hi"
            - "Universe!"
            set-environment:
              - greeting: "Warm greetings!"

        - sequential:
          - print:
            - "{{env:welcome}}"
          - execute:
            - "echo {{env:greeting}}"

  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          imagePullSecrets:
            - name: container-registry-secret
          containers:
            - name: roiergasias
              image: docker.io/ankursoni/roiergasias-operator:workflow
              command: ["./cmd/main", "./cmd/hello-world/hello-world.yaml"]
              volumeMounts:
                - name: yaml
                  mountPath: /root/cmd/hello-world
              resources:
                requests:
                  memory: "100Mi"
                  cpu: "100m"
                limits:
                  memory: "200Mi"
                  cpu: "200m"
          restartPolicy: Never
