apiVersion: batch/v1
kind: Job
metadata:
  name: roiergasias-job
  namespace: roiergasias
spec:
  backoffLimit: 3
  template:
    spec:
      imagePullSecrets:
        - name: container-registry-secret
      containers:
        - name: roiergasias
          image: docker.io/ankursoni/roiergasias:latest
          command: ["./cmd/main", "./cmd/machine-learning/machine-learning.yaml"]
          volumeMounts:
            - name: machine-learning
              mountPath: /root/cmd/machine-learning
      restartPolicy: Never
      volumes:
        - name: machine-learning
          hostPath:
            path: {{ .Values.hostPath }}
            type: Directory
